{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}
{% set release = '.'.join(version.split('.')[:2]) %}

package:
  name: q2-sourmash
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  build:
    - python 3.5*
    - setuptools

  run:
    - python 3.5*
    - setuptools
    - numpy
    - pandas
    - scipy 
    - Cython
    - khmer>=2.1,<3
    - sphinx
    - alabaster
    - recommonmark
    - sphinxcontrib-napoleon


test:
  imports:
    - q2_sourmash 
    - qiime2.plugins.sourmash

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
